### ISSUE TITLE
Too Many JSON datas from onlinecount

### ISSUE THREAD

**Issue by Jareczeq** [kronthto/api.vi0lation.de#3]
Hi!
I would like to ask why there is so much of this data from http://api.vi0lation.de/api/chromerivals/onlinecount. Are even from 2020 year.

**Comment by kronthto** [comment]
The data returned is already limited to 200 days in the past - otherwise the response would be even larger because there is data collected since late 2018.

Still, there is a datapoint every 10 minutes for all those 200 days so it adds up.

I will consider reducing it to a daily average for older data points.

**Comment by kronthto** [comment]
It will naturally become less over time as only hourly points are added anymore.
